Num1 = int(input("enter number: "))
Num2 = int(input("enter number: "))
Num3 = int(input("enter number: "))
Num4 = int(input("enter number: "))
Num5 = int(input("enter number: "))
print(Num1 + Num2)
print(Num2 - Num3)
print(Num3 * Num4)
print(Num4 // Num5)
print(Num3 % Num4)